### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/outreach-docs#244]
This repository doesn't include a license. Would be good to add one for the works in `monero-outreach-docs`.

**Comment by lh1008** [comment]
This is a good idea. Which license do you consider fits best for the outreach content?

**Comment by lh1008** [comment]
We're still commenting about this @erciccione. This hasn't been placed in the drawer. Just adding a comment so we can keep up with the conversation.

**Comment by erciccione** [comment]
This is important. Right now we are all working in a grey area. Because of the absence of a license, all content on this repo and monerooutreach.org cannot technically be copied, distributed, or modified. While this might seems a technicality, it could be the cause of big problems in case any of the people who contributed to this repo will decide to complain about it for a reason or another.

I'm also surprised there is still no license at all on monerooutreach.org itself. This should be fixed as soon as possible, itcan creates big problems.

ping @thunderosa @xmrhaelan

**Comment by Thunderosa** [comment]
Yeah, sorry, I thought we had settled this. lh, you pretty much run this repo so I'm fine with whatever you think is best.

**Comment by erciccione** [comment]
@Thunderosa it's not just about the repo, this is related not only to the translations posted here, but to all outreach documents.

**Comment by Thunderosa** [comment]
Yes, I understand but as I've mentioned before, I do not feel that a blanket policy on-site is the right answer and we're not quite equipped yet for a case-by-case scheme which is really the right answer.

For what reason would a contributor complain? Our amounts are humble, but we offer a stipend to everyone who contributes. Some have not accepted payment, no one has complained to my knowledge.

Elsewhere, we've not sat idle. A lot of effort has gone into labeling sources where appropriate, but this is mostly stuff we can't grant a licence for in the first place. As far as I know all the things on our site that don't have a source label came from MO direct and I can't imagine any of us giving a fuck about someone else using it.

**Comment by erciccione** [comment]
@thunderosa i think you are misunderstanding why having a license is important. Please take a look at  https://choosealicense.com/no-permission/

Not having a license doesn't mean everybody can do whatever they want, but the opposite. If you want people to use the docs from outreach without restrictions, then you need a license. Without a license, you expose the outreach workgroup to unnecessary liabilities and risks.

**Comment by Thunderosa** [comment]
You've been heard, but listen. We're not 100% sure we can even grant a licence, there's no entity here. In most cases the creators are a group of avatars who are the original owners, but are also not legal entities. Can a non-entity grant a transferable licence to another non-entity for them to grant to the world?

A blanket licence would simplify that, like with an open-source software repo, but that will be problematic for us by either being too restrictive at times and/or being so full of exceptions as to become confusing or worse, misleading. The other concern would be us inadvertently granting rights for something that's not ours.

Where we think we can meet you halfway is to label positively, piece-by-piece, with the appropriate licence, if any. Most of this will be CC-BY-NC (Attribution-NonCommercial 4.0 International). All future work from us will have it's licence established upfront in the master so that it accompanies the piece when it's in the Ecosystem repo or Taiga etc. We've added a licensing tag to our system to append the appropriate CC blurb, licence and link to the bottom of each page in each language.

You can see it on the bottom of the Patent piece:
https://www.monerooutreach.org/stories/monero-patents.html

We are updating prior work with this, but it'll take a week or so to update everything. We'll be ganging that up with some minor layout changes we wanted to make, so that's why it'll take a little longer.

I think you brought up a good point, and I hope this solves it. I think it will allow MO to remain flexible and truthful and that was my main concern.

**Comment by erciccione** [comment]
> We're not 100% sure we can even grant a licence, there's no entity here. In most cases the creators are a group of avatars who are the original owners, but are also not legal entities. Can a non-entity grant a transferable licence to another non-entity for them to grant to the world?

I think there is still confusion about what a license is ad what's its purpose. You don't need to be an entity of any kind. The copyright holder is the person who created the content. Doesn't matter if you are a legal or natural entity. There is at least one case that come in my mind where a photographer was denied copyrights from an award-winning photo, because the actual person who clicked the button to shoot the photo wasn't a person, but a monkey. So the copyrights are owned by the monkey. Marginal fun fact, but makes the point :)

> Where we think we can meet you halfway

This is weird to read :P You are not doing a favour to me by introducing a license, i'm just pointing out the issue. Eventual problems would be for the copyright holders like you, not for me.

> piece-by-piece, with the appropriate licence

If that's the intention that you must make sure the same is done in this repository. In theory you should also make sure the copyright holders of the work you are licensing (the people who created the content) are fine with licensing their work. Since the intention was always to release the content to the public this shouldn't be a problem.

**Comment by Thunderosa** [comment]
It was David Slater who claimed the copyright on that image. It was PETA who tried to argue that the monkey was the copyright owner but it was dismissed by every court and/or copyright office it was brought before. The monkey does not own a copyright.

**Comment by erciccione** [comment]
Right, the example was wrong and i went by memory. Monkeys aside, the point still stands.

**Comment by Thunderosa** [comment]
Let's agree to disagree. The main thing is that functionally, you and I are in agreement that we should label content in a way so that people feel comfortable using it if they'd like, but I don't think it will mean anything legally.

**Comment by erciccione** [comment]
> I don't think it will mean anything legally.

This is not correct, as i already explained. See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository.

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

This is also pointed out in the other link i posted earlier (https://choosealicense.com/no-permission/). The only reason to add a license is to not be vulnerable from a legal point of view, so i wouldn't say it doesn't mean anything legally.

Anyway, i spent way too much time on this issue, which doesn't even involve me directly. Do whatever you think it's best :)
