### ISSUE TITLE
accept_monero_stickers_en.md

### ISSUE THREAD

**Issue by b068931cc450442b63f5b3d276ea4297** [monero-ecosystem/outreach-docs#285]
Unfortunately, there are several errors with the links at https://www.monerooutreach.org//merchants/we-accept-monero-stickers.html:

- it is linked to .../MoneroMerchant/... and not to .../MoneroMerchants/... which means that the file is not found at the moment.
- the same link /We-Accept-Monero-Sign-en-4x1.33.svg is always used (not 3 different ones as indicated) 
- it always refers to the English file in each language and not to customized ones in the respective languages

A suggestion for improvement of the formatting of the table in accept_monero_stickers_en.md I submitted a pullrequest.

**Comment by lh1008** [comment]
Yes, these errors happened because they were not correctly edited and were doing some changes to the section. It has been updated to not confuse those who navigate the website but the section is going to change.

Thank you for noticing these errors on the site. 

Take a look at how is now: https://www.monerooutreach.org/merchants/we-accept-monero-stickers.html

Closing the Issue but open to comments :).
